### ISSUE TITLE
Doesn't work without .tern-project

### ISSUE THREAD

**Issue by rivertam** [carlitux/deoplete-ternjs#10]
That's fine, but it's a real head-scratcher for those of us who assumed there'd be a default. Please document that you need one (and an example .tern-project file would be nice, too)

**Comment by carlitux** [comment]
Thanks... just looked and tern has that feature.

**Comment by rivertam** [comment]
Has what feature? Doesn't work without .tern-project? I was able to run the tern server okay, I think. Either way, I think most of the users here are coming from tern_for_js which doesn't require it, so most of us might get caught by surprise. =)

**Comment by carlitux** [comment]
I am going to remove that requirement as ternjs does the search for it or fallback to default setup

**Comment by carlitux** [comment]
@rivertam please update and test... also read the document now and please give me feedback is something is missed or is difficult to understand.

**Comment by rivertam** [comment]
Seems to be working. =)

The documentation isn't entirely understandable. I'd replace it with

> If no .tern-project file is found in the current file's directory or its ancestors, deoplete-ternjs will start the ternjs server in the current working directory:
> 
> :pwd
> allowing ternjs use the default setup.

I don't actually know what "starting the ternjs server in the current working directory" implies, but that's because I'm not familiar with the ternjs server in general, so I could be wrong on that. =)

**Comment by carlitux** [comment]
Well really tern is the tool that do the hard work start a server where we can do requests http://ternjs.net/ , so this start the server and parse the .tern-port to know what port was opened.

This only integrates deoplete with tern.
