### ISSUE TITLE
Very very slow.

### ISSUE THREAD

**Issue by nhooyr** [carlitux/deoplete-ternjs#12]
Using this source slows down deoplete massively for me. No idea why, moment I remove it, deoplete is blazing fast. Even if I'm not in a javascript file.

**Comment by carlitux** [comment]
What is your tern project file?

**Comment by nhooyr** [comment]
@carlitux none, I'm not even in a tern project. I'm programming in go but this plugin slows down deoplete a ton.

**Comment by carlitux** [comment]
That is weird, tern source shouldn't be started unless a javascript file is
being edited.

**Comment by carlitux** [comment]
Please update and looks now avoid to do anything if not js file is editing.

**Comment by nhooyr** [comment]
LGTM
