### ISSUE TITLE
Question regarding the autocompletion list

### ISSUE THREAD

**Issue by ahmedelgabri** [carlitux/deoplete-ternjs#14]
I'm not sure if this is `deoplete-ternjs` or `deoplete` issue but I noticed that comparing the autocomplete list to YCM plugin, YCM usually has more options, I wonder why?

![tern](https://cloud.githubusercontent.com/assets/63876/14588377/84c9618c-04c8-11e6-9f3e-89b53d76bbed.gif)

**Comment by carlitux** [comment]
I think depends how is using tern, how defines defaults I really don't know you can compare with ternjs online demo.

**Comment by iamcco** [comment]
I usually has the to config for myself

rplugin/python3/deoplete/source/ternjs.py:

![image](https://cloud.githubusercontent.com/assets/5492542/14592766/e13778fa-0554-11e6-93c3-a0888bda199e.png)

**Comment by ahmedelgabri** [comment]
@carlitux this is my tern config, which was in the demo. And I have zero custom configs for deoplete or YCM. So I assume I should get the same results.

```json
{
    "libs": [
        "ecma5",
        "ecma6",
        "browser"
    ],
    "loadEagerly": [],
    "async": true,
    "plugins": {
        "doc_comment": {
          "fullDocs": true
        },
        "complete_strings": {},
        "es_modules": {},
        "modules": {},
        "node": {},
        "commonjs": {},
        "node_resolve":{}
    }
}
```

For tern online http://ternjs.net/doc/demo/ if you do the following and trigger autocomplete <kbd>CTRL</kbd>+<kbd>SPACE</kbd> you will get the same result as YCM.

```js
[].
Array.
Object.
```

and I can confirm that after adding @iamcco edits to the plugin it did match YCM and ternjs online demo, so maybe this should be in the plugin by default or even as _opt-in_ settings.

**Comment by carlitux** [comment]
@ahmedelgabri yes I think should be the default as I migrated tern_for_vim to use in deoplete I never thought about that.

@iamcco could you do a pull request?

**Comment by ahmedelgabri** [comment]
Thanks @iamcco for the PR! and thanks @carlitux
