### ISSUE TITLE
don't report error message if .tern-project have syntax error

### ISSUE THREAD

**Issue by butterflyfish** [carlitux/deoplete-ternjs#16]
```json
{
    "libs": [
        "browser"
    ],
}
```

tern report message:
```sh
tern
Bad JSON in /Users/michael/x/.tern-project: Unexpected token } in JSON at position 41
```

after removing , after ], completion work.

**Comment by carlitux** [comment]
This is not a bug.

This is JSON format... this is not a JS file so you can't have a comma after last field-value or array item.
 Should be in this way:

```json
{
    "libs": [
        "browser"
    ]
}
```
