### ISSUE TITLE
Stops working after certain amount of time

### ISSUE THREAD

**Issue by simonsmith** [carlitux/deoplete-ternjs#18]
Hey,

I have an issue where Tern will stop working in neovim after a while and the only way to fix is to restart neovim which I assume forces the Tern server to restart as well. This only started in the last few days or so. Is there anyway for me to debug what might be going on here?

Thanks!

**Comment by carlitux** [comment]
You can use system utilities to see the performance, memory usage, cpu usage by tern... I think that is the best way to debug.

**Comment by simonsmith** [comment]
Not sure I understand? I don't see `tern` in my `htop` or Activity Monitor. Is there a way to print debug messages to `:mess`?

**Comment by carlitux** [comment]
if you want to edit code self.debug()... are you using latest code, I don't having this issue or at least I didn't noticed?

https://github.com/carlitux/deoplete-ternjs/blob/master/rplugin/python3/deoplete/sources/ternjs.py#L156

**Comment by simonsmith** [comment]
Using latest versions of deplete and this plugin. If I open neovim and interact with some JS it works as expected. If I leave neovim for 5-10 minutes it just stops working with no error messages. I'm assuming the tern server is getting stopped somehow.

**Comment by simonsmith** [comment]
I reverted to https://github.com/carlitux/deoplete-ternjs/commit/190410b02204f72fd00c44927861e336eefeae64 and it works as expected again

**Comment by carlitux** [comment]
@simonsmith that branch was creating a lot of tern instances... and for me was using more than 100% of cpu, let me know if this is happening

**Comment by carlitux** [comment]
@simonsmith you can test new commit? I added the flag to keep listening ternjs.

**Comment by simonsmith** [comment]
That seems to have resolved it! Thanks @carlitux
