### ISSUE TITLE
Tern stops working after a while.

### ISSUE THREAD

**Issue by nicknikolov** [carlitux/deoplete-ternjs#20]
Hi, thanks for making this library. I have finally settled in a near-perfect JS environment. However when working all of a sudden stops giving suggestions:
![screen shot 2016-05-26 at 10 58 23](https://cloud.githubusercontent.com/assets/1440420/15571008/ba4919f2-2330-11e6-9190-340138c09b67.jpg)

When I restart neovim it works again.
![screen shot 2016-05-26 at 11 00 10](https://cloud.githubusercontent.com/assets/1440420/15571090/f48aedc0-2330-11e6-927d-ac9f61c99a17.jpg)

My version is 0.1.4

I have a fairly simple config that you can see here:
http://pastebin.com/v10upH1j

I use a global tern-config in my home directory:
```
{
  "libs": [
    "browser"
  ],

  "plugins": {
    "node": {},
    "requirejs": {
      "baseURL": "./",
      "paths": {}
    }
  }
}
```

I'm sorry for not being able to provide much useful information as I don't know how I can debug this. Any help would be appreciated.

**Comment by carlitux** [comment]
looks like is same that this https://github.com/carlitux/deoplete-ternjs/issues/18

**Comment by nicknikolov** [comment]
Thanks, seems to be working so far.
