### ISSUE TITLE
Tern stops every time .tern-port is created.

### ISSUE THREAD

**Issue by nicknikolov** [carlitux/deoplete-ternjs#24]
Hey there,

 I wasn't sure if this is the problem but it's been a while now and every time tern stops (inside neovim) I go to project folder and see a .tern-port file created. I delete it and restart neovim and it's fine but the pesky little thing spawns itself quite often recently. Is this is a known issue? Is there some option to turn it off?

EDIT: To clarify, I only have a global .tern-config file, never local per project. Inside there is this:
```
{
  "ecmaVersion": 6,
  "libs": [
    "browser",
    "ecma5",
    "ecma6"
  ],

  "plugins": {
    "node": {},
    "commonjs": {}
  }
}
```

Thanks!

**Comment by carlitux** [comment]
You can try with local(per project) one and test if works well?

**Comment by mhartington** [comment]
Hey seeing this as well. Even with a local config file being used.
What other info would you like?

**Comment by carlitux** [comment]
there was two commits 
https://github.com/carlitux/deoplete-ternjs/commit/e3696421e9101478f83f6ed5b0cddab879450a09
and the doc
https://github.com/carlitux/deoplete-ternjs/commit/274244ddf19d871d0b9d77f9faac918d532ee9f4

If you are not using tern_for_vim the .tern-port will not be deleted if neovim breaks or for some reason neovim is not quitted normally and you have to delete it.

**Comment by nicknikolov** [comment]
@carlitux @mhartington I think what helped me is putting a global .tern-port

**Comment by mhartington** [comment]
I ended up just using tern_for_vim as @carlitux suggested, which is fine. Was starting to miss the TernDoc info any ways 😁 

Tern_for_Vim + Deoplete-tern is a great flow. Thanks for the plugin!
