### ISSUE TITLE
Weird issue with files when opened from inside a project.

### ISSUE THREAD

**Issue by ahmedelgabri** [carlitux/deoplete-ternjs#27]
I have a weird issue, I have a project with a `.tern-profile` file. When I open any `.js` file from inside that project folder, tern completion doesn't work _**but**_ if I open the same exact from a different directory everything is working fine!

This is the project `.tern-project`
```json
{
  "libs": [
    "ecma5",
    "ecma6",
    "browser",
    "jquery"
  ],
  "loadEagerly": [],
  "async": true,
  "dontLoad":[
    "node_modules",
    "dist",
    "tmp",
    "vendor",
    "public"
  ],
  "exclude": [
    "node_modules/**",
    ".git/**",
    "*.min.js",
    "*.prod.js",
    "*.debug.js",
    "tmp",
    "vendor"
  ],
  "plugins": {
    "doc_comment": {
      "fullDocs": true
    },
    "complete_strings": {},
    "es_modules": {},
    "modules": {},
    "node": {},
    "commonjs": {},
    "node_resolve":{}
  }
}
```

This is my global `.tern-config`

```json
{
  "libs": [
    "ecma5",
    "ecma6",
    "browser"
  ],
  "loadEagerly": [],
  "async": true,
  "plugins": {
    "doc_comment": {
      "fullDocs": true
    },
    "complete_strings": {},
    "es_modules": {},
    "modules": {},
    "node": {},
    "commonjs": {},
    "node_resolve":{}
  }
}
```

##### This is what I tried so far, but nothing changes:
- Deleting the project `.tern-project`.
- Replace the content of `.tern-project` with `~/.tern-config` content.
- I thought it's might be a problem with `tern` path since the project uses a different node version that the system. But I saw #26. So I added the config & even `:echo g:tern_path` returns the right path.
- Switched the node version to the system one.
- If I go up one level up the folder structure everything works normally.
- Deleted my `Session.vim` created by https://github.com/tpope/vim-obsession & started with blank session.

No idea how can I debug this any further & how to fix this problem.

**Comment by carlitux** [comment]
@ahmedelgabri I tested and it is working fine... take a look if you have .tern-port on your project directory, if there is any you have to delete it.

**Comment by ahmedelgabri** [comment]
Thanks! @carlitux but why is that a problem in the first place? I thought `.tern-port` is required for `tern_vim` to work?

**Comment by carlitux** [comment]
It happens to me when vim crashed or my computer do, too.

.tern-port is created when tern starts so if you are using tern_for_vim it will start an instance server and this source just request to that tern instance parsing .tern-project to know where do http requests.
