### ISSUE TITLE
What are the lines in the README doing?

### ISSUE THREAD

**Issue by CrashyBang** [carlitux/deoplete-ternjs#29]
Hey what do the following lines do?

```vim
let g:tern_request_timeout = 1
let g:tern_show_signature_in_pum = '0'
```

Cheers.

**Comment by carlitux** [comment]
`let g:tern_request_timeout = 1`

is the time waited when requesting to ternjs

`let g:tern_show_signature_in_pum = '0'`

change the way how autocomplete is displayed
