### ISSUE TITLE
align type names

### ISSUE THREAD

**Issue by nhooyr** [carlitux/deoplete-ternjs#3]
Looks really weird to me.

<img width="1440" alt="screen shot 2016-03-01 at 4 42 32 pm" src="https://cloud.githubusercontent.com/assets/10180857/13442951/adb0c19c-dfcc-11e5-869e-7ce5ad14c8db.png">

**Comment by carlitux** [comment]
@nhooyr please test now

**Comment by nhooyr** [comment]
LGTM
