### ISSUE TITLE
Add remove_async_await config for babel/es7 projects

### ISSUE THREAD

**Issue by jsl9208** [carlitux/deoplete-ternjs#31]
Thank you for this awesome plugin!

I have an issue using it in a babel/es7 project. Since async/await keywords have not been supported by tern yet, some code fragments will crash tern and stop the further completion, like:
```js
app.use(async (ctx) => { // No tern completion after this line
    return;
});
```

Deleting the async/await keywords before sending buffer to tern solves this problem. Is it ok to add a config like `g:tern_remove_async_await` for this? I can create a PR for it.

**Comment by carlitux** [comment]
@jsl9208 do you think there isn't another way with tern config?

I just tested and tern still works for me, completions inside the blocks is not provided but outside still works.

**Comment by jsl9208** [comment]
@carlitux No, there is no tern config for it.. 

Thank you for the test, yes it works outside the functions. I found that tern didn't crash but respond with no completions inside the block.

The only way I could think of is replace those keywords with spaces. It is kind of dirty but works for me.

**Comment by carlitux** [comment]
@jsl9208 maybe the best way is to wait for support https://github.com/ternjs/tern/issues/814 do you think we lost a lot?

If we lost a lot please create a PR with that.

**Comment by jsl9208** [comment]
@carlitux not lost a lot. It seems to be supported soon, better to wait. Thank you : )
