### ISSUE TITLE
Autocomplete for require/import statements does not work properly

### ISSUE THREAD

**Issue by AlexMasterov** [carlitux/deoplete-ternjs#32]
**deoplete-ternjs**

![deoplete-ternjs](http://i.imgur.com/VjBibmq.png)

**tern_for_vim**

![tern_for_vim](http://i.imgur.com/uJfRfpY.png)

**Comment by carlitux** [comment]
@AlexMasterov could you paste your config?

Also take a look at this https://github.com/carlitux/deoplete-ternjs/issues/25 most of the errors on this is about how your plugins works. Many developers install plugins to pair quotes or snippets that modify source code.

The source only has to return candidacies and deoplete insert into the buffer. Maybe we can try to find a way to hack this and implement some way to pair the quotes.

**Comment by AlexMasterov** [comment]
@carlitux thanks for such a quick reply.

With `<C-x><C-o>`: modules not showing in suggestions.
With `deoplete#manual_complete()` trigger:  only `'|`  and `'react-|` works, but adds quote pairs.

Minimal config for testing:

**nvim**
```vim
" deoplete.nvim
inoremap <silent> <expr> <Tab> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()

" deoplete-ternjs
let g:deoplete#sources = {}
let g:deoplete#sources.javascript = ['ternjs']

" tern_for_vim
let g:deoplete#omni#functions = {}
let g:deoplete#omni#functions.javascript = ['tern#Complete']
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.javascript = '\h\w*\|\h\w*\.\%(\h\w*\)\|[^. \t]\.\%(\h\w*\)'
```
**.tern-project**
```json
{
  "libs": [
    "ecmascript",
    "browser"
  ],
  "plugins": {
    "es_modules": {},
    "node_resolve": {},
    "requirejs": {
      "baseURL": "./",
      "paths": {}
    },
    "doc_comment": {}
  },
  "loadEagerly": [
    "src/*.js"
  ]
}
```

**Comment by carlitux** [comment]
@AlexMasterov @razor-x @wavded 

Please update and review, looking at https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/deoplete_jedi.py I found the way to enable import and require autocomplete so you don't need to call `deoplete#manual_complete()` any more.

Please test and let me know if something is wrong, few times is not autocompleting for me maybe something missed on regular expression if any of you have time to review the REs please do a pull request.

Here is where you can see the regular expresions.

https://github.com/carlitux/deoplete-ternjs/blob/5500ae246aa1421a0e578c2c7e1b00d858b2fab2/rplugin/python3/deoplete/sources/ternjs.py#L47

https://github.com/carlitux/deoplete-ternjs/blob/5500ae246aa1421a0e578c2c7e1b00d858b2fab2/rplugin/python3/deoplete/sources/ternjs.py#L351

**Comment by carlitux** [comment]
@AlexMasterov on your screenshoots I see you are using react. The issue I found happens when

I have it works
```js
import React from 'rea
```

and here it stops working (most the time)
```js
import React from 'reac
```

But when deleting with backspace start completing again.

Please confirm

**Comment by AlexMasterov** [comment]
Works fine  :+1:
Thank you!
