### ISSUE TITLE
--no-port-file argument ignored

### ISSUE THREAD

**Issue by sherzinger** [carlitux/deoplete-ternjs#33]
I'm using NVIM v0.2.0-6-g3979c6c on macOS with deoplete, deoplete-ternjs and tern_for_vim.

These are my options:
let g:tern#command = ["tern"]
let g:tern#arguments = ["--persistent", "--no-port-file"]

I would expect no more .tern-port files to appear, but they still do.

**Comment by carlitux** [comment]
@sherzinger 

1.- If you use tern_for_vim deoplete-ternjs won't start a new tern instance it will use tern_for_vim instance.
2.- tern_for_vim start the instance with .tern-port file.
3.- both needs to find at least one .tern-port to know where request.

The config you have is for tern_for_vim not for deoplete-ternjs what this means you are telling tern for vim start tern instance with no .tern-port file and when deoplete-ternjs starts and no .tern-port found itself start a new instance with .tern-port.

You can see here that the config is for tern_for_vim
https://github.com/ternjs/tern_for_vim/blob/master/script/tern.py#L109
