### ISSUE TITLE
Use Tern "trigger" commands

### ISSUE THREAD

**Issue by akrueger** [carlitux/deoplete-ternjs#38]
Is it possible to utilize a trigger command to open up autocompletion with Tern such as is described here: https://ternjs.net/doc/demo/index.html#simple

For instance the autocomplete trigger command is `ctrl-space`.

I am not sure if that would be initiated here or in deoplete itself.

Thanks

*** **Edit** ***

I tried this out and it seems to do what I need:

https://vi.stackexchange.com/questions/9468/cant-get-deoplete-plugin-working-in-neovim

If you have anything to add that you think would help, please add, if not feel free to close. 

Thanks!

**Comment by carlitux** [comment]
@akrueger you have to do with deoplete and you have to setup as you read in the second link.
