### ISSUE TITLE
Loading the index when editing vuejs files with vueim

### ISSUE THREAD

**Issue by motanelu** [carlitux/deoplete-ternjs#39]
Hi,

I'm using deoplete-ternjs to edit [vue](https://vuejs.org/) files. The file is composed from 3 sections, <template> (for HTML), <script> (for JS) and <style> (for CSS / SaSS / etc.)

I'm using [vueim](https://github.com/pocke/vueim) for easy editing, which identifies each section and opens a new buffer for it. For example, given the file: `/Projects/vue/components/MyComponent.vue`, when I run `:VueimTabEditScript` to edit the JS, will create a "virtual" file with the following descriptor: `vueim://Projects/vue/components/MyComponent.js` and this confuses deoplete-tern which yields the following error:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/tudor/vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 98, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/Users/tudor/.vim/bundle/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 353, in gather_candidates
[deoplete]     result = self.completation(pos) or []
[deoplete]   File "/Users/tudor/.vim/bundle/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 309, in completation
[deoplete]     data = self.run_command(command, pos)
[deoplete]   File "/Users/tudor/.vim/bundle/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 182, in run_command
[deoplete]     self.start_server()
[deoplete]   File "/Users/tudor/.vim/bundle/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 94, in start_server
[deoplete]     portFile = os.path.join(self._project_directory, ".tern-port")
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/posixpath.py", line 89, in join
[deoplete]     genericpath._check_arg_types('join', a, *p)
[deoplete]   File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/genericpath.py", line 143, in _check_arg_types
[deoplete]     (funcname, s.__class__.__name__)) from None
[deoplete] TypeError: join() argument must be str or bytes, not 'NoneType'
[deoplete] Could not get completions from: ternjs.  Use :messages for error details.
```

However if I run `:set ft=javascript` on the .vue file, autocomplete something and it works once, then it will work even in the new buffer opened by `:VueimTabEditScript`, which leads me to believe that the index is lazy-loaded on demand. Is there a way to programmatically force it to load the index, like calling `:call <magic>` to load the index before doing the `:VueimTabEditScript`, which will prompt the script to work on the new buffer? 

Or maybe I can set the location from where the files should be loaded? 

Thank you,

**Comment by carlitux** [comment]
@motanelu I don't have time to debug this but looks like :VueimTabEditScript don't create a reference over current project or don't really create, the code uses `expand('%:p:h')` to get the project directory.

If you can collect more info we could solve this.
