### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by ahmedelgabri** [carlitux/deoplete-ternjs#45]
I started to get this error(s) like 2-3weeks ago & it's totally random. I don't really know when or how to reproduce
<img width="1174" alt="screen shot 2017-04-04 at 21 22 43" src="https://cloud.githubusercontent.com/assets/63876/24674862/5d779dd6-197d-11e7-8078-b479d079aa1c.png">

**Comment by carlitux** [comment]
@ahmedelgabri reading the traceback I can't see this source on it. Any other info to find the bug?

**Comment by ahmedelgabri** [comment]
Will try to keep an eye on this to try & find any useful info.

**Comment by ahmedelgabri** [comment]
Here is a gif that might be helpful
![deoplete-tern](https://cloud.githubusercontent.com/assets/63876/24678078/6f97bc1a-1989-11e7-992c-cfdbfd6f52ee.gif)

**Comment by carlitux** [comment]
could you remove custom settings for deoplete and try without them, then start adding them to know what is happening still nothing useful.

I am not getting that error.

**Comment by ahmedelgabri** [comment]
I removed all deoplete options & still getting the error.

here is my setup 

https://github.com/ahmedelgabri/dotfiles/blob/HEAD/neovim/.config/nvim/init.vim#L26-L30
https://github.com/ahmedelgabri/dotfiles/blob/d98b5c24ca7502adb7fbb0e4938ae073e7e99c7b/neovim/.config/nvim/after/plugin/deoplete.vim

**Comment by carlitux** [comment]
could you try to disable this to be sure https://github.com/ahmedelgabri/dotfiles/blob/HEAD/neovim/.config/nvim/init.vim#L35

This are my settings: https://github.com/linkux-it/vimgalaxy/search?utf8=%E2%9C%93&q=deoplete&type=

**Comment by ahmedelgabri** [comment]
I have disabled `deoplete-flow` for the past nearly two days & the error still happens, I will start commenting out parts of [here](https://github.com/ahmedelgabri/dotfiles/blob/d98b5c24ca7502adb7fbb0e4938ae073e7e99c7b/neovim/.config/nvim/after/plugin/deoplete.vim) to see if it's related

**Comment by tamoore** [comment]
I get a similar error to this, trying to debug it at the moment. I think it might be related to nvm, but not 100% sure right now. It happens in some of my projects and not in others.

**Comment by tamoore** [comment]
```
[deoplete] Traceback (most recent call last):
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/tmoore/.dotfiles/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]   File "/Users/tmoore/.dotfiles/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/tmoore/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_length.py", line 20, in filter
[deoplete]   File "/Users/tmoore/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_length.py", line 20, in filter
[deoplete]     return [x for x in context['candidates']
[deoplete]     return [x for x in context['candidates']
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] Could not filter using: <deoplete.filter.matcher_length.Filter object at 0x110f7d3c8>.  Use :messages for error details.
[deoplete] Could not filter using: <deoplete.filter.matcher_length.Filter object at 0x110f7d3c8>.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/tmoore/.dotfiles/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]   File "/Users/tmoore/.dotfiles/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/tmoore/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_fuzzy.py", line 29, in filter
[deoplete]   File "/Users/tmoore/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/matcher_fuzzy.py", line 29, in filter
[deoplete]     return [x for x in context['candidates']
[deoplete]     return [x for x in context['candidates']
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] Could not filter using: <deoplete.filter.matcher_fuzzy.Filter object at 0x110f76e80>.  Use :messages for error details.
[deoplete] Could not filter using: <deoplete.filter.matcher_fuzzy.Filter object at 0x110f76e80>.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/tmoore/.dotfiles/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]   File "/Users/tmoore/.dotfiles/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/tmoore/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/sorter_rank.py", line 23, in filter
[deoplete]   File "/Users/tmoore/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/sorter_rank.py", line 23, in filter
[deoplete]     key=lambda x: -1 * rank[x['word']]
[deoplete]     key=lambda x: -1 * rank[x['word']]
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] Could not filter using: <deoplete.filter.sorter_rank.Filter object at 0x110f7d630>.  Use :messages for error details.
[deoplete] Could not filter using: <deoplete.filter.sorter_rank.Filter object at 0x110f7d630>.  Use :messages for error details.
[deoplete] Traceback (most recent call last):
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/tmoore/.dotfiles/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]   File "/Users/tmoore/.dotfiles/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 186, in merge_results
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]     context['candidates'] = f.filter(context)
[deoplete]   File "/Users/tmoore/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_abbr.py", line 24, in filter
[deoplete]   File "/Users/tmoore/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/converter_truncate_abbr.py", line 24, in filter
[deoplete]     for candidate in context['candidates']:
[deoplete]     for candidate in context['candidates']:
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] TypeError: 'NoneType' object is not iterable
[deoplete] Could not filter using: <deoplete.filter.converter_truncate_abbr.Filter object at 0x110f769b0>.  Use :messages for error details.
[deoplete] Could not filter using: <deoplete.filter.converter_truncate_abbr.Filter object at 0x110f769b0>.  Use :messages for error details.
```

**Comment by tamoore** [comment]
Apologies, turns out this was caused by `deoplete-flow` not having access to the `flow` bin. However, for anyone coming to this issue, make sure that you have tern installed in the node version you're currently using with `nvm` that may also cause a similar error.

**Comment by ahmedelgabri** [comment]
In my case, I have flow in my path & tern installed globally. I even removed `deoplete-flow` completely but I'm still getting the errors.

**Comment by tamoore** [comment]
what happens when you run `!tern` or `!flow` in the command prompt in vim? Does it return with a status 0?

**Comment by ahmedelgabri** [comment]
Both work fine `!tern` & `!flow`

**Comment by carlitux** [comment]
Guys I don't have that issue but just I added error messages maybe will help us to find the error please test it.

**Comment by ahmedelgabri** [comment]
This just happened, this is what I'm dealing with. 

<img width="1323" alt="screen shot 2017-04-14 at 11 04 13" src="https://cloud.githubusercontent.com/assets/63876/25039118/601eb984-2102-11e7-8e57-980f428eb7e2.png">
<img width="1202" alt="screen shot 2017-04-14 at 11 04 29" src="https://cloud.githubusercontent.com/assets/63876/25039115/601dc74a-2102-11e7-8390-ca5806a9a51d.png">
<img width="1237" alt="screen shot 2017-04-14 at 11 04 38" src="https://cloud.githubusercontent.com/assets/63876/25039117/601e927e-2102-11e7-8479-954d34187237.png">
<img width="1133" alt="screen shot 2017-04-14 at 11 04 50" src="https://cloud.githubusercontent.com/assets/63876/25039114/601db764-2102-11e7-9e02-3db308b4cd6c.png">
<img width="1217" alt="screen shot 2017-04-14 at 11 05 02" src="https://cloud.githubusercontent.com/assets/63876/25039116/601e0db8-2102-11e7-91b2-c475fae0c8b4.png">

**Comment by wavded** [comment]
I can attest that I get either the same or similar errors from time to time but do not have a clear way to reproduce.  If I get one again I will pass it on.

**Comment by carlitux** [comment]
@ahmedelgabri thank you very much! I will review now what is happening

**Comment by carlitux** [comment]
I tried to fix other bugs and improve logs here.

At some point looks like the error appears on python client, but honestly I don't think so... I hope we can find soon what is the error.

**Comment by mike3run** [comment]
i get that error from time to time sometimes 😕

**Comment by carlitux** [comment]
@mike3run any way to reproduce it? I am working all days with it and no errors.

**Comment by carlitux** [comment]
@ahmedelgabri @tamoore @wavded @mike3run are you still getting this error?

**Comment by mike3run** [comment]
@carlitux not really as of recently, but i remember that it used to happen while entering git in fugitive like after a commit for example

**Comment by mike3run** [comment]
![screen shot 2017-08-15 at 10 58 41 pm](https://user-images.githubusercontent.com/7088511/29346793-61418ece-820d-11e7-9aed-2b3210ddb43b.png)

Just got the error today but with deoplete in a scss file so its safe to assume this is not related to deoplete-tern project but actually to deoplete itself

**Comment by carlitux** [comment]
@mike3run you are right.
