### ISSUE TITLE
plugin changes syntax/italix highlighting

### ISSUE THREAD

**Issue by adamki** [carlitux/deoplete-ternjs#46]
Just getting into building a new `init.vim` and all is well. Would love to integrate this plugin into my neovim... but it seems to conflict with some syntax highlighting as well as italicizing.

syntax plugins being used: 
```
  call dein#add('othree/yajs')
  call dein#add('pangloss/vim-javascript')
  call dein#add('jelera/vim-javascript-syntax')
  call dein#add('maxmellon/vim-jsx-pretty')
  call dein#add('elzr/vim-json')
  call dein#add('othree/javascript-libraries-syntax.vim')
```

more syntax config:
```
  colorscheme one
  syntax on
  set background=dark 
  hi htmlArg gui=italic
  hi Comment gui=italic
  hi Type    gui=italic
  hi htmlArg cterm=italic
  hi Comment cterm=italic
  hi Type    cterm=italic
```

![jun-01-2017 12-57-31](https://cloud.githubusercontent.com/assets/10334352/26698215/f1cfc372-46c9-11e7-8ac8-71f80540917a.gif)

**Comment by adamki** [comment]
screen share is a bit blurry. But on the right pane... I add `caritux/deoplete-ternjs` and then run `:so %`
Meanwhile, you can see lots of the syntax hi update on the left

**Comment by carlitux** [comment]
@adamki just tested with my setup and this:

```vim
  colorscheme drakula
  syntax on
  set background=dark 
  hi htmlArg gui=italic
  hi Comment gui=italic
  hi Type    gui=italic
  hi htmlArg cterm=italic
  hi Comment cterm=italic
  hi Type    cterm=italic
```
And nothing happens looks like that works with `one` color scheme the error should be in one of that plugins or deoplete this plugin just returns a list of candidates and doesn't do any draws.

**Comment by carlitux** [comment]
Also that is on load the plugin or on computation?

**Comment by adamki** [comment]
I agree, I don't know why it would affect syntax highlighting. 

However, I have verified by `clean_install`ing the plugins. If I start with `deoplete-ternjs` removed... all of my syntax highlighting is intact and working. 

Next, I add `deoplete-ternjs` and run `:call dein#install()`. 

Finally, I open a brand new nvim session and my syntax highlights are gone. Im currently working with a minified `init.vim` as seen below:

```
if (!isdirectory(expand("$HOME/.config/nvim/repos/github.com/Shougo/dein.vim")))
  call system(expand("mkdir -p $HOME/.config/nvim/repos/github.com"))
  call system(expand("git clone https://github.com/Shougo/dein.vim $HOME/.config/nvim/repos/github.com/Shougo/dein.vim"))
endif

" set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim/
set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.config/nvim'))
call dein#add('Shougo/dein.vim')
call dein#add('rakr/vim-one')
call dein#add('othree/yajs')
call dein#add('pangloss/vim-javascript')
call dein#add('jelera/vim-javascript-syntax')
call dein#add('maxmellon/vim-jsx-pretty')
call dein#add('Shougo/denite.nvim')
call dein#add('Shougo/deoplete.nvim')

if dein#check_install()
  call dein#install()
  let pluginsExist=1
endif

call dein#end()
filetype plugin indent on


let $NVIM_TUI_ENABLE_TRUE_COLOR=1
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1   " sets ENV var for true colors
set termguicolors                     " enable true colors
syntax on                                       " enable syntax
set background=dark                             " must go before :colorscheme
colorscheme one                                 " must go after set bg
let g:one_allow_italics = 1                     " italix in vim-one


hi htmlArg gui=italic
hi Comment gui=italic
hi Type    gui=italic
hi htmlArg cterm=italic
hi Comment cterm=italic
hi Type    cterm=italic

```

**Comment by adamki** [comment]
Closing. Seems to have been a residual plugin dispite my best efforts to clean. Dein does quite a bit of caching. My apologies for the alarm
