### ISSUE TITLE
slow first-time text insert

### ISSUE THREAD

**Issue by sudavid4** [carlitux/deoplete-ternjs#47]
I've noticed an annoying delay when first inserting text using your plugin. I suppose it's because of the time it takes for the tern server to load. Is it possible to make this async? I don't mind having my completions kick-in a while later but having a delay when first entering text is rather bothering. Thanks

**Comment by carlitux** [comment]
@sudavid4 doing async is not an option because deoplete is async, one option should be to set tern timeout too short

**Comment by sudavid4** [comment]
thanks, your suggestion works great. 

A little parentheses for the next people coming here: changing the `g:tern_request_timeout` might not be the best idea since this is the variable that tern-for-vim will be looking at. I ended up hardcoding it in the source code(`rplugin/python3/deoplete/sources/ternjs.py`) to 100ms and commenting out this line of code
```py
        # if vim.eval('exists("g:tern_request_timeout")'):
        #     self._tern_timeout = float(vim.eval('g:tern_request_timeout'))
``` 
this solves my problem really great though. Thank you very much @carlitux

**Comment by Shougo** [comment]
deoplete is async.  But deoplete-ternjs should use the thread for server.
If deoplete-ternjs blocks, it block deoplete completion.

**Comment by carlitux** [comment]
@Shougo I can see there is new option for async sources `is_async` now reading doc to update code, thanks!

**Comment by carlitux** [comment]
@sudavid4 please test and let me know if changes improved performance for you, please note that variables was changed read the read me file.

**Comment by sudavid4** [comment]
@carlitux It's working really great now. thanks a lot
