### ISSUE TITLE
additional options

### ISSUE THREAD

**Issue by sudavid4** [carlitux/deoplete-ternjs#48]
Hi @carlitux 
what do you think about adding some options to control what's shown in the popup menu?
Specifically I would like to:
1. not show object prototype methods
2. not show function signature - because the popup menu ends up taking to much screen space
3. change the `menu` option from `[tern]` to simply `[js]`
then we could leave all the defaults as is and give `g:deoplete#tern#show_signature_in_pum`, `g:deoplete#tern#menu_symbol` and `g:deoplete#tern#hide_object_prototype` options to control these settings. 

If you like the idea I may try to implement it (although I don't really know python at all, I suppose I can find my way around for that) and make a pr

for now I have those hardcoded in a [fork of your project](https://github.com/sudavid4/deoplete-ternjs/blob/master/rplugin/python3/deoplete/sources/ternjs.py) but I would rather be synced to your master
10x

**Comment by carlitux** [comment]
- New options to control requests to tern, please read README file so you can setup as you need the UI result.
- Change `[TernJS]` to `[js]`is not a good idea because there are a few tool if not many that do same as ternjs so would be good to keep tool identity

**Comment by sudavid4** [comment]
fair enough. 10x
