### ISSUE TITLE
Doesn't complete the same as tern_for_vim

### ISSUE THREAD

**Issue by alexlafroscia** [carlitux/deoplete-ternjs#5]
I've been trying for the past two days, but just can't seem to get this working correctly.  I've been using a simple test program, shown below:

```javascript
export class Person() {
  returnMe() {
    return this;
  }

  dontReturnMe() {
    return undefined;
  }
}

const p = new Person();
p.
```

With my cursor after the `.` on the last line, if I invoke `tern_for_vim` through the `omnifunc` that it provides, I get prompted with both `returnMe` and `dontReturnMe` as functions.  However, if I invoke Deoplete (I have it set to a keyboard shortcut rather than automatically completing as I type) from that same position, I get no options at all.

**Comment by carlitux** [comment]
I tested and it is working for me

![session](https://cloud.githubusercontent.com/assets/40538/13550569/7059b564-e2f7-11e5-8962-d9427249ee70.gif)

**Comment by alexlafroscia** [comment]
Weird! I just can't get it working. What are your Deoplete-related settings? I'm wondering what in my configuration is conflicting.

**Comment by carlitux** [comment]
Really don't need any setup... I will be adding if anyone needs it.

**Comment by alexlafroscia** [comment]
You use all of the default settings for Deoplete itself?

**Comment by carlitux** [comment]
yes, please also see if you have the latest code on first commits there was a lot of bugs.

**Comment by alexlafroscia** [comment]
Yeah, I have the most recent version.  I guess I'll start disabling other plugins and see what conflicts... I'll be sure to post whatever it is for future reference.

**Comment by alexlafroscia** [comment]
Found the issue -- major stupidity on my part.  I didn't have `tern` installed globally, it was only installed locally in the `tern_for_vim` Vim plugin's directory.

**Comment by carlitux** [comment]
Maybe also my mistake I just updated the README file

**Comment by alexlafroscia** [comment]
Would it be possible to bundle it as part of the plugin? `tern_for_vim` does that, which might make it easier to set up.

**Comment by carlitux** [comment]
really it is only a package.json on it and you have to do 

```bash
npm install
```

what could be 

```bash
npm install -g tern
```

**Comment by alexlafroscia** [comment]
Yeah, that's a good point. I guess that doesn't make much sense.
