### ISSUE TITLE
Fallback to global tern-project configuration

### ISSUE THREAD

**Issue by JodusNodus** [carlitux/deoplete-ternjs#51]

**Comment by carlitux** [comment]
@JodusNodus what is the issue? could you add deoplete debug data please.

**Comment by JodusNodus** [comment]
No, it would just be nice if it used global .tern-project file when none is found in the current working directory

**Comment by carlitux** [comment]
@JodusNodus already done, but .tern-project file should be in up in path of the project.

**Comment by JodusNodus** [comment]
That is what i mean. When no tern-project file is found in the path of the project it should fallback on the global tern-project configuration. If u open a file without a tern-project file tern does not work.

**Comment by carlitux** [comment]
Please send me the deoplete logs, and basic vim config to reproduce. It is working for me.
