### ISSUE TITLE
Function signature disappears

### ISSUE THREAD

**Issue by gunar** [carlitux/deoplete-ternjs#52]
![deoplete-ternjs mp4](https://user-images.githubusercontent.com/7684574/30091513-50542642-9290-11e7-933a-47d28771ba65.gif)

Would there be a way to keep the tooltip visible during arguments filing?

Thanks in advance.

**Comment by carlitux** [comment]
It is not issue of this source, that is the way that https://github.com/Shougo/deoplete.nvim works. The way I solved is keeping enable the preview and the following config:

```vim
let g:deoplete#sources#ternjs#types = 1
let g:deoplete#sources#ternjs#types = 1

  " This to close preview when insert mode leaves
  autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
  autocmd InsertLeave * if pumvisible() == 0|pclose|endif
```

I hope this helps.

**Comment by gunar** [comment]
Thank you!
This is what I ended up using
```viml
" Commented out not to disable preview window
" set completeopt-=preview

" Close preview when insert mode leaves
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" This was hiding the preview window, so it's commented out
" autocmd InsertLeave * if pumvisible() == 0|pclose|endif
```
