### ISSUE TITLE
Tern results take a long time to appear

### ISSUE THREAD

**Issue by simonsmith** [carlitux/deoplete-ternjs#59]
Example of how long it takes to appear on `React.` (5-6 seconds) - https://cl.ly/oFFu

I've tried running my own tern server with `--verbose` and I can see several request/response before the final response comes back with all the completions. The query sent to the server looks like:

```js
 "query": {
    "type": "completions",
    "types": false,
    "depths": false,
    "docs": false,
    "filter": true,
    "caseInsensitive": false,
    "guess": true,
    "sort": false,
    "expandWordForward": true,
    "omitObjectPrototype": false,
    "includeKeywords": false,
    "inLiteral": true,
    "file": "#0",
    "end": {
      "line": 29,
      "ch": 6
    },
    "lineCharPositions": true
  }
```

My deoplete settings are:

```vim
if s:has_plugin('deoplete.nvim')
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#sources = {}
  let g:deoplete#sources.python = ['ultisnips']
  let g:deoplete#sources.javascript = ['buffer', 'tern']
endif

if s:has_plugin('deoplete-ternjs')
  let g:tern_request_timeout = 1
  let g:tern_show_signature_in_pum = '0'
  let g:tern#command = ['tern']
  let g:tern#arguments = ['--persistent']
  let g:deoplete#sources#ternjs#timeout = 1
  let g:deoplete#sources#ternjs#tern_bin = '/Users/simonsmith/.nvm/versions/node/v8.9.0/bin/tern'
endif
```
This also seems to block just normal buffer completions from appearing as well. If I disable this plugin then autocompletions from the same buffer appears instantly.

Any suggestions are welcomed :)

**Comment by carlitux** [comment]
Looks like you are using tern_for_vim, aren't you?

I tested and I get the result with only one query this one:

```js
Request: {
  "query": {
    "type": "completions",
    "types": true,
    "depths": true,
    "docs": true,
    "filter": true,
    "caseInsensitive": false,
    "guess": true,
    "sort": false,
    "expandWordForward": true,
    "omitObjectPrototype": false,
    "includeKeywords": false,
    "inLiteral": true,
    "file": "#0",
    "end": {
      "line": 2,
      "ch": 6
    },
    "lineCharPositions": true
  },
  "files": [
    {
      "type": "full",
      "name": "test.js",
      "text": "import React from 'react';\n\nReact.\n"
    }
  ]
}
```

The heavy process is startup tern but I with latest code this happens into a thread and returns the control to deoplete with async mode.

I had same issue with autocomplete box using vim-flow

Please provide more info to reproduce if still getting the issue

**Comment by simonsmith** [comment]
I've actually disabled tern_for_vim as it causes perf issues and seems abandoned development wise. 

Could the cause be dependent on how many files are imported into a module? Wondering if several requests are made based on that? I tried a simple file as you have done above and it's just one request made.

**Comment by carlitux** [comment]
Confirmed with a big file tern is slow I will review and improve this one.

**Comment by carlitux** [comment]
Please test I improved the gather candidates with async. If you are using vim flow has same issue so delays will appear.

**Comment by simonsmith** [comment]
It seems faster, which is awesome but I think I have a reproducible bug.

1. Open a file, trigger a lookup of some methods like `React.` or `this.`
1. Methods are returned in autocomplete
1. Delete and try again, nothing is returned.
1. Type any character and then delete it and results appear as expected.

Video of issue: https://cl.ly/oOwr

I can reproduce the above video each time I open nVim fresh each time. It does not clear if I simply close and reopen the buffer.

**Comment by simonsmith** [comment]
Additionally I can only seem to get results back on `React.` (`createElement`, `PureComponent` etc) if I spawn my own `tern` server.

**Comment by carlitux** [comment]
@simonsmith we will have delays when we start neovim because it have to start the server and there is a delay.

The other I will be debugging.

**Comment by carlitux** [comment]
@simonsmith sorry for delay could you confirm this with latest tern/deoplete/deoplete-ternjs versions.

I can't reproduce it.
