### ISSUE TITLE
autocomplete menu show different result

### ISSUE THREAD

**Issue by iamcco** [carlitux/deoplete-ternjs#6]
javascript code:
```javascript
var obj = {
    name: 'aioiyuuko',
    showName: function() {
        console.log(this.name);
    }
};

$1
$2
$3obj.name

```
the $1,$2 and $3 is the position of the cursor. i type `obj.` at $1 i get the right result of autocomplete , but when i type `obj.` at $2 i just got the Omni autocomplete result, the same issue is that i type `console` or `console.`  at $3 position, just get the Omni autocomplete result.

mininit.vim
```viml
" vim-plug {
    call plug#begin('~/dotfiles/nvim/plugged')

    " deoplete and sources about {
        Plug 'Shougo/deoplete.nvim'
        Plug 'carlitux/deoplete-ternjs', { 'for': 'javascript' }
    " }

    call plug#end()

" }

" plugins {

    " deoplete.nvim {
        let g:deoplete#enable_at_startup = 1
        let g:deoplete#max_list = 15
        inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
        function! s:my_cr_function()
            return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
        endfunction
        inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    " }
" }

```

**Comment by carlitux** [comment]
I tested and it is working for me.

min setup https://github.com/carlitux/deoplete-ternjs/blob/master/tests/ternjs-deoplete.vim and also setting `:set syntax=javascript` is not firing omnicomplete unless I call it.

**Comment by iamcco** [comment]
maybe you don't understand what i describe because my poor English.

look at the two screen of the **cursor's position** and the autocomplete menu below:

![1](https://cloud.githubusercontent.com/assets/5492542/13720876/c5922b58-e84f-11e5-91dc-590adaf2392f.png)

![2](https://cloud.githubusercontent.com/assets/5492542/13720877/cc696c84-e84f-11e5-954a-71addde5c827.png)

**Comment by carlitux** [comment]
Please update and test again, I think now is fixed.

**Comment by iamcco** [comment]
It works well now, thanks!
