### ISSUE TITLE
Not working correctly

### ISSUE THREAD

**Issue by arnsa** [carlitux/deoplete-ternjs#62]
Hello,

so I've been banging my head around for like 5 hours today, and this is as far as I've got. Let's say I open up vim editor and type in this:

`[1, 2, 3].fi`

Vim should show a popup with autocomplete suggestions, but nothing happens. What I have to do to make it work is press tab, then backspace and then tern seems to start working. I don't have to do this "tab thing" anymore, I just need to do it once I start the vim editor. Does anybody have any ideas what might be wrong? It behaves the same on both: vim and neovim. Here's my .vimrc file: https://gist.github.com/arnsa/3ce831a5d7fd9f5c4e6135a8f61175f0

**Comment by carlitux** [comment]
Would be good start and get working just deoplete with deoplete-ternjs, then add tern_for_vim, and then all your custom setup.

**Comment by arnsa** [comment]
@carlitux well, if I remove tern_for_vim package, it still works the same way :/. Any ideas?

**Comment by carlitux** [comment]
no sure something in your setup maybe is doing that usually after the second character typed autocomplete start.

**Comment by arnsa** [comment]
@carlitux well, you've seen my whole .vimrc file. What else can I provide you? I really want to make it work :/.

**Comment by arnsa** [comment]
Okay, I've figured it out: setting deoplete#auto_complete_start_length to 1 solved the problem.
