### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by codeinabox** [carlitux/deoplete-ternjs#63]
I've been getting this error quite a bit lately

> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/matt/.vim/plugged/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 317, in completation
>     data = self.run_command(command, pos)
>   File "/Users/matt/.vim/plugged/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 258, in run_command
>     data = self.make_request(doc, silent)
>   File "/Users/matt/.vim/plugged/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 229, in make_request
>     req = opener.open(self._url, payload)
>   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
>     response = self._open(req, data)
>   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
>     '_open', req)
>   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1346, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [Errno 61] Connection refused

**Comment by carlitux** [comment]
@codeinabox please update and test.

**Comment by codeinabox** [comment]
Thank you. Issue seems to have gone away but will reopen if the case is otherwise
