### ISSUE TITLE
"--no-port-file" tern argument not applying

### ISSUE THREAD

**Issue by michaelghinrichs** [carlitux/deoplete-ternjs#64]
I cannot seem to get this argument to work:
```
let g:tern#arguments = ["--no-port-file"]
```

I am still getting the `.tern-port` file created in any project I open Vim in....

Any ideas for why this might not be working?

**Comment by carlitux** [comment]
Already that setup is for tern_for_vim, it is not for this source. This source search for file `.tern-port` if the file exists uses the port in that file if the file doesn't exists start a tern instance and start the port in the new created file.
