### ISSUE TITLE
Please make deoplete-ternjs work with vim 8

### ISSUE THREAD

**Issue by Jeansen** [carlitux/deoplete-ternjs#65]
Deoplete works fine in vim 8, but for javascript and tern it seems that I cannot use omnifunc (see https://github.com/Shougo/deoplete.nvim/issues/244). Deoplete-ternjs needs nvim. I'd like to see this plugin also work with vim 'plain old' vim. Or am I missing something and it actually works (somehow)?

**Comment by carlitux** [comment]
@Jeansen you have to install deoplete and deoplete-ternjs, if you have setup deoplete ternjs should work with no changes. You have to install ternjs and be available with in your path.

Later you can customize it.

**Comment by Jeansen** [comment]
@carlitux  I cannot install deoplete-ternjs, because it needs nvim, but I use plain vim 8. I tried though, but without any luck.

**Comment by carlitux** [comment]
why you can't install? could you describe better your issue please.

**Comment by Jeansen** [comment]
OK, I think I got it. Problem seems to be, that I used the wrong tern binary. I cannot use tern by nvm. Did not see the note in ternjs readme. Installing nvim via pip, installing ternjs and using the system tern works :-)

**Comment by carlitux** [comment]
@Jeansen already you can use with nvm but you have to config all your system to use it. It is good you can use now this in the simplest form later you will be able to improve it.

**Comment by Jeansen** [comment]
Since a couple of days (I updated my python packages via pip), I get this one:

```
[deoplete] Traceback (most recent call last):
  File "/home/marcel/.vim//plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 107, in _add_source
    source = Source(self._vim)
  File "/home/marcel/.vim//plugged/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 35, in __init__
    'deople
te#sources#ternjs#filetypes', []))
  File "/home/marcel/.local/lib/python3.7/site-packages/pynvim/api/common.py", line 138, in get
    return self.__getitem__(key)
  File "/home/marcel/.local/lib/python3.7/site-packages/pynvim/api/common.py", line 110, in __getitem__
    raise transform_keyerror(exc)
  File "/hom
e/marcel/.local/lib/python3.7/site-packages/pynvim/api/common.py", line 108, in __getitem__
    return self._get(key)
  File "/home/marcel/.local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/marcel/.local/lib/python3.7/si
te-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: 'deoplete#sources#ternjs#filetypes'
Could not load source: /home/marcel/.vim//plugged/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py.  Use :messages / see above for error detai
ls.
```
Whenever I open a non-javascript file.

Any ideas?

**Comment by zhmars** [comment]
https://github.com/carlitux/deoplete-ternjs/blob/307f9c3beb178026d122d9ab3825e4640dd1c29a/rplugin/python3/deoplete/sources/ternjs.py#L34-L35

`vim.vars.get()` is not working anymore on pynvim 0.4.0, deoplete has fixed this in https://github.com/Shougo/deoplete.nvim/commit/f64b1b471839d59ba9d4a333112f5f46ea28ed31

**Comment by Jeansen** [comment]
@zhmars Thanks for the udpate. But I still get this error, even after updating everything.

**Comment by Jeansen** [comment]
The commit message says: Don't use vim.vars.get(): it does not work in Vim8. Now the question is, is it fixed (but still does not work in Vim 8) Or should it be fixed because it does not work in Vim 8? ;-)

**Comment by carlitux** [comment]
@Jeansen I just pushed a simple change hope this fix your issue. If not should send me a reproducible bug. 

The issue is only with vim.

**Comment by Jeansen** [comment]
@carlitux Yep, that seems to have fixed it. Thank you very much.
