### ISSUE TITLE
Looks line tern was stopped or crashed. Delete .tern-port file and restart [n]vim

### ISSUE THREAD

**Issue by bnftco** [carlitux/deoplete-ternjs#66]
I got this message from neovim while editing javascript file. And after that, I think auto completion on javascript(ex) fs.readFileSync) does not work well.

I use node v.8.9.4 and neovim v0.2.2
Also I added screenshot.
<img width="610" alt="2018-05-18 14 25 23" src="https://user-images.githubusercontent.com/5221401/40217362-57a968be-5aa7-11e8-8ef6-54e547759ac0.png">

**Comment by carlitux** [comment]
That means that deoplete-ternjs can't connect to ternjs. You have to delete .tern-port and restart neovim

**Comment by bnftco** [comment]
Thanks! I will try it at my workday!

**Comment by diartyz** [comment]
@carlitux 
`.tern-port` is not necessary, can we remove it ?
I create a pr about this. https://github.com/carlitux/deoplete-ternjs/pull/71

**Comment by carlitux** [comment]
@diartyz we already need `.tern-port` file. Sometimes vim/nvim won't finish well and won't finish ternjs correctly and `.tern-port` won't be removed. If you see this error you have to delete by hand the file.

**Comment by zhmars** [comment]
hi, @carlitux

I am new to this plugin. Could you please tell me why the `.tern-port` file is need for deoplete-ternjs ?

Because I did some search about other similar project

- [YouCompleteMe / L421](https://github.com/Valloric/ycmd/blob/8082b6f241bd911452cfd7f21f8a70fce00abf63/ycmd/completers/javascript/tern_completer.py#L421)
- [tern_for_vim / L15](https://github.com/ternjs/tern_for_vim/blob/14109c81b219c2737f39168dfef269d0d311731f/autoload/tern.vim#L15)
- [nvim-cm-tern / L33](https://github.com/roxma/nvim-cm-tern/blob/14fbc4c30d6beafd1943ae6b0af700955833dd30/pythonx/cm_sources/cm_tern.py#L33)

and found all of them use `--no-port-file` flags to avoid write the `.tern-port` file.

Another question, Can we get a config flag like `g:deoplete#sources#ternjs#tern_arguments` for someone who want pass `--no-port-file` flag to the tern command ? Or a flag to tell deoplete-ternjs where to store the `.tern-port` file ?

English is not my mother tongue; please excuse any errors on my part.

**Comment by carlitux** [comment]
@zhmars deoplete only works for autocomplete and some vim users also wants other tools that ternjs offers. And instead of using two tern instances we need .tern-port

Maybe would be good to add and option to avoid file but right now I don't have time to do it.

`--no-port-file` could be de default and adding a global variable should enable port file

**Comment by zhmars** [comment]
Thanks for your detailed explanation. It would be great to have this feature.

**Comment by pwang2** [comment]
This error will throw after you open nvim and type you first "dot" but tern is not started yet.  It will happen frequently if you have a low spec computer especially. 

I personally think port file is not needed and we'd better use a local installed tern instance in plugin folder.

**Comment by carlitux** [comment]
@pwang2 if you have low spec computer I think ternjs is killed by OS, removing that won't help you. But you can try and sending a PR.

About installation, there are many environments that we can't assume it. You can setup your PATH env to setup for your needs.

**Comment by jtomes123** [comment]
Hey guys, I don't know if this is a good solution but it seems to work for me, although I have been using vim for only about a day. I have added this code into my .vimrc, it checks if there is .tern-port file in the cwd and deletes it.

`function! TernPrep()
    if !empty(glob(join([getcwd(), ".tern-port"], "/")))
        echo ".tern-porn exists, deleting with result:"
        echo delete(fnameescape(join([getcwd(), ".tern-port"], "/"))) == 0 ? "Success" : "Fail"
    endif
endfunction

autocmd VimEnter * :call TernPrep()`

**Comment by FuzzOli87** [comment]
I've been running into this issue yesterday after updating neovim and plugins. I look for the .tern-port file, which is usually created on the directory where I started neovim from but in this case, it is not. Any other place where it could be put?

**Comment by abepark01** [comment]
I seem to be experiencing this issue as soon as I try to attempt autocomplete and there is no .tern-port file when I search for it.

nvim 0.3.1
neovim 0.2.6
tern@0.22.2
deoplete-ternjs 4b6276019a1491cc5003a0b007ca1aaeab671f57
```
Exception in thread Request Completion:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/admin/.vim/bundle/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 318, in completation
    data = self.run_command(command, pos)
  File "/Users/admin/.vim/bundle/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 259, in run_command
    data = self.make_request(doc, silent)
  File "/Users/admin/.vim/bundle/deoplete-ternjs/rplugin/python3/deoplete/sources/ternjs.py", line 227, in make_request
    req = opener.open(self._url, payload)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by carlitux** [comment]
Maybe you are with tern version with issue try update

**Comment by daliusd** [comment]
I have reproducible scenario on my machine that results in this error.

OS: Ubuntu 18.04.1 LTS
Vim: Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)

1. Run vim test.js, enjoy ternjs integration working.
2. Quit vim. Tern seems to be closed uncleanly. .tern-port file is still available while tern is not running.
3. Run vim test.js again - get this error, as deoplete-ternjs (and tern_for_vim) assumes that if .tern-port file can be found then tern is running. While it seems tern simply crashed because of not clean tern server stop.

**Comment by carlitux** [comment]
@daliusd this happens all the time?

**Comment by daliusd** [comment]
@carlitux Yes - it is 100% reproducible and my system is littered with .tern-port files. I can use @jtomes123 workaround as usually I work with single Vim instance. I imagine that different Vim version might not have this problem. If there is a way I could help with this I would be happy.

**Comment by carlitux** [comment]
@carlitux maybe is related with vim, I will work soon in an improve, or if you can create a PR would be great. Sorry for the issue.

**Comment by daliusd** [comment]
@carlitux I could create PR but I need some guidance. I have looked into the code and there is clean-up in __del__ method. So theoretically tern server should be stopped. It looks like vim is not waiting for plugin to complete the work or something similar is happening. It would be ideal if vim stopped tern properly.

If we can't stop tern from vim properly then maybe we should check if server is actually running on port read from ".tern-port". What's your suggestion?

**Comment by daliusd** [comment]
Here are some things I have managed to dig out:

It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits. (from https://docs.python.org/3/reference/datamodel.html#object.__del__)

Potential fix would be to implement VimLeavePre command:

autocmd deopleteternjs VimLeavePre * call python_command_call_to_kill_tern()

Maybe I will implement that later.

**Comment by carlitux** [comment]
Sorry for delay.

> autocmd deopleteternjs VimLeavePre * call python_command_call_to_kill_tern()

Maybe this is not a good option. All start and stop of sources is done by deoplete.

What I think is to remove dependency of `.tern-port` file as I know `tern_for_vim` already do this now, so the idea is add the param to avoid `.tern-port` creation and parse `stdout` result to get the port.

**Comment by daliusd** [comment]
Yes, tern_for_vim already does this. Personally for me that would be OK (and I assume for many people who are not using tern_for_vim).

**Comment by daliusd** [comment]
Lastly if deoplete is responsible for proper clean-up maybe fix must be implemented there.

**Comment by daliusd** [comment]
Update. I have created issue in deoplete.nvim https://github.com/Shougo/deoplete.nvim/issues/905. As well I have created pull request https://github.com/carlitux/deoplete-ternjs/pull/81 with workaround to this problem.

**Comment by raphaellopes** [comment]
I Had the same problem with 0.23 version of tern installed. But as @abepark01 said, I downgrade to 0.21 and now its working again, even when a close and reopen the vim.

I changed my Plug install to:
```
Plug 'carlitux/deoplete-ternjs', { 'do': 'npm install -g tern@0.21' }
```

I don't know if is good practice to fix the version here, but it is working for me

**Comment by carlitux** [comment]
no more `.tern-port` file will be created, needs to update to latest ternjs and update also this source.

**Comment by sparky005** [comment]
I am suddenly getting this issue on the latest tern version. If i downgrade to 0.21 the issue seems to go away. Is there some compatibility issue with the latest version of tern still?

**Comment by carlitux** [comment]
@sparky005 hi, sorry as I am using lsp server didn't know if you have a PR I can merge it

**Comment by sparky005** [comment]
Sorry @carlitux I'm not sure what the problem is so I can't make a PR haha
Deoplete itself seems to have been superseded by a new thing: https://github.com/Shougo/ddc.vim so maybe I should just move to that  ¯\_(ツ)_/¯
