### ISSUE TITLE
is there a better input pattern?

### ISSUE THREAD

**Issue by plexigras** [carlitux/deoplete-ternjs#68]
if i have `import {|} from './mymath'` `|` being the cursor and press `<c-space>` in http://ternjs.net/doc/demo/#ES6 i see `Pi` and `halve` but if i am in vim i have to write `P` to get to see `Pi` and `h` to see `halve` which obviously isn't great.

**Comment by carlitux** [comment]
you have to define the mappings to call deoplete.
