### ISSUE TITLE
Tern takes a lot of Memory around 1.0 GB

### ISSUE THREAD

**Issue by aswinmohanme** [carlitux/deoplete-ternjs#69]
I noticed that after some time the memroy usage of tern process was around 1.0 GB. 

Here is my .tern-project file
```
{
  "libs": [ ],
  "loadEagerly":[
  ],
  "plugins": {
    "node": { },
    "requirejs" : { },
    "es_modules" : { },
    "doc_comment": { "fullDocs": true },
    "complete_strings": {}
  }
}
```

This was while working on  a React Native Project. I'm using the latest version of all plugins and tern

**Comment by carlitux** [comment]
looks like https://www.npmjs.com/package/tern-jsx uses acorn-jsx and https://www.npmjs.com/package/tern-react is another plugin for ternjs

Test on your side what is good for you
