### ISSUE TITLE
Doesn't work with Shougo/echodoc

### ISSUE THREAD

**Issue by michaeltintiuc** [carlitux/deoplete-ternjs#72]
Echodoc seems to work with deoplete PHP, Go and Python plugins but fails to display any output with this one. I tried setting this `let g:deoplete#sources#ternjs#types` to both 1 and 0, but no luck.
Was anyone enable to get this working?

**Comment by carlitux** [comment]
@michaeltintiuc I don't know how echodoc works, this should be reported in that repository and if feature is missed please create a PR with it.

**Comment by michaeltintiuc** [comment]
@carlitux Looks like this might go back and forth :disappointed: 
https://github.com/Shougo/echodoc.vim/issues/12

**Comment by carlitux** [comment]
It was reported on 2016 and was not reported here. I don't use echodoc. When I have time I will look at it

**Comment by michaeltintiuc** [comment]
Thanks @carlitux I'll try to look into this myself and report back, thanks for your time!

**Comment by carlitux** [comment]
@michaeltintiuc implemented
