### ISSUE TITLE
how to set for reactjs

### ISSUE THREAD

**Issue by MartiniGo** [carlitux/deoplete-ternjs#78]
Hi carlitux，When I was writing react, I couldn't get some react method completion.like this，
![11](https://user-images.githubusercontent.com/41671631/48658347-38d28d80-ea7b-11e8-9c44-6508a97586dd.png)
in vscode is  well。
![2](https://user-images.githubusercontent.com/41671631/48658352-45ef7c80-ea7b-11e8-9ca8-8883d8681bf4.png)

this is my `.tern-project` setting
```
{
  "libs": [
    "browser",
    "ecmascript",
    "jquery",
    "react",
    "underscore"
  ],
  "plugins": {
    "node": {},
    "esmodules": {},
    "jsx":{},
  }
}
```
and  this is my min init.vim
```
let g:deoplete#sources#ternjs#filetypes = [
	\ 'jsx',
	\ 'javascript.jsx',
	\ 'javascript'
	\ ]
let g:deoplete#sources#ternjs#timeout = 3
let g:deoplete#sources#ternjs#types = 1
let g:deoplete#sources#ternjs#docs = 1
```

**Comment by MartiniGo** [comment]
> Please take a look VS is using same version as you are using in vim. Also take care you have compatible tern with plugins you are using.
> 
> ![screenshot from 2018-11-17 15-19-03](https://user-images.githubusercontent.com/40538/48664944-d2e70580-ea7c-11e8-83e5-2478c896710f.png)

@carlitux  wow  its cool，I have been writing go with vim. But recently I need some react. I am still a newbie on js. Can you share your relevant configuration?like`.tern-project` and min `init.vim`

**Comment by MartiniGo** [comment]
I am a newcomer to vim. Looking forward to getting your better help。I don't know where the problem is. Google has not been solved for a long time, which makes me very depressed
![sceenshot](https://user-images.githubusercontent.com/41671631/48668075-886a9500-eb1f-11e8-8b20-2055738d5591.gif)

**Comment by MartiniGo** [comment]
Well, I have a new problem in the process of reinstalling. When I select the completion list, the buffer will always blink, Whenever I choose to complete it once, the buffer will flash once.how to solve this problem.
![sceenshot](https://user-images.githubusercontent.com/41671631/48669727-74d22500-eb45-11e8-961c-82f13a713c18.gif)

**Comment by MartiniGo** [comment]
I have the same problem with him, but I can't understand his solution. Sorry, I am a gopher and I just started learning react. https://medium.com/@jrwillette88/tern-why-it-breaks-and-how-to-fix-it-8d1677df05f9

**Comment by carlitux** [comment]
@MartiniGo sorry for late reply. Please read this to see what community find the correct versions for **tern** and **tern-jsx** https://github.com/carlitux/deoplete-ternjs/issues/66.

About blinking if I am not wrong that is because you have the +preview option. You could search/ask here https://github.com/Shougo/deoplete.nvim.

And about post, that is how **tern** start. If engine see one module start collecting metadata so at first time you will have a delay you can setup to .tern-project http://ternjs.net/

I hope this helps.

**Comment by MartiniGo** [comment]
It started working, but it still made me confused. I need to create the `.tern-project` file in the root directory of my project, which is under gopath. When I create it under the `~` directory it won't work,

**Comment by ihechiwilliams** [comment]
@glepnir please can you share your config file
