### ISSUE TITLE
Not an editor command: TernRename

### ISSUE THREAD

**Issue by Cyperwu** [carlitux/deoplete-ternjs#80]
Seems that the original tern_for_vim functions are not available. Should I use both plugins simultaneously？

**Comment by carlitux** [comment]
@Cyperwu this is just a source for [deoplete](https://github.com/Shougo/deoplete.nvim) and [deoplete](https://github.com/Shougo/deoplete.nvim) it is just for autocompletion. So if you want the other features you have to install `tern_for_vim`
