### ISSUE TITLE
deoplete-ternjs should not send to tern full vue file

### ISSUE THREAD

**Issue by last-partizan** [carlitux/deoplete-ternjs#85]
Hi

I was using deoplete-ternjs to edit vue files and it crashed like in #76 
It was becouse this plugin was sending full vue file, but ternjs expects only javascript part.

This crash is fixed in ternjs now: https://github.com/ternjs/tern/pull/1023

But anyway, plugin should be modified to send only script part to tern.

**Comment by carlitux** [comment]
As I commented in https://github.com/carlitux/deoplete-ternjs/issues/76 this is not an issue of **tern** nor **deoplete-ternjs**.

To be able to edit this kind of files you have to find a plugin/parser to get **tern** working properly.

I edit react files with no issues at all.

BTW.- Looks like neither official tern plugins works https://github.com/ternjs/tern_for_vim/issues/172

**Comment by last-partizan** [comment]
What sort of plugin/parser it would be? and for what: vim or tern?

React files is almost normal javascript, afaik. Vue is <template>+<script>+<style> in one file, but tern expects only script part.

**Comment by carlitux** [comment]
Tern one, for react there is https://www.npmjs.com/package/tern-jsx
