### ISSUE TITLE
freezing 

### ISSUE THREAD

**Issue by nhooyr** [carlitux/deoplete-ternjs#9]
Having deoplete-ternjs stops deoplete from working at all for me. Not sure why, manual invocations freeze neovim and the autocomplete doesn't work at all.

**Comment by nhooyr** [comment]
Bisecting shows commit `c7376a2331c8d4ecac3dafa3cf1965fd948a030a` to be the problem. Its the `Add timeout configuration` commit.

**Comment by iamcco** [comment]
i have the same issue

**Comment by carlitux** [comment]
fixed... thank you very much guys
